name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build and validate bicep

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '14'

        - name: Install dependencies
          run: npm install

        - name: Set up .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '5.0.x'

        - name: Restore dependencies
          run: dotnet restore

        - name: Build the project
          run: dotnet build --no-restore --configuration Release

        - name: Run tests and collect code coverage
          run: dotnet test MyFunctionApp.Test/MyFunctionApp.Test.csproj --no-build --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

        - name: Upload code coverage report
          uses: actions/upload-artifact@v2
          with:
              name: code-coverage-report
              path: MyFunctionApp.Test/coverage.cobertura.xml